title: "IIA Hub"
description: "Página interna de la carrera Ingeniería en Inteligencia Artificial"
baseurl: "/iia-hub"   # si publicás en usuario.github.io/nombre-repo, poné aquí "/nombre-repo"
url: "https://udesa-iia.github.io"

markdown: kramdown
plugins: []

# Se excluyen del build de Jekyll
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
